version: '3.4'

x-service-restart-policy: &service-restart-policy
  restart_policy:
    condition: on-failure
    delay: 60s
    window: 100s

services:
  oracle.api:
    image: ${DOCKER_REGISTRY-}oracle.api
    build:
      context: .
      dockerfile: src/Oracle.API/Dockerfile
    ports:
      - "5077:5077"
      - "7143:7143"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7143;http://+:5077
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ./:/https:ro
    depends_on: 
      oracle-db:
        condition: service_started
    deploy:
      <<: *service-restart-policy # Allow Oracle to fully start
        
  oracle-db:
    image: "gvenzl/oracle-xe"
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=testpassword
      - ORACLE_DATABASE=APIDB
      - APP_USER=testuser
      - APP_USER_PASSWORD=testpassword
    volumes:
      - oracle-volume:/opt/oracle/oradata
    deploy:
      <<: *service-restart-policy
        
volumes:
  oracle-volume: